shell.run("cd /")
shell.run("mkdir VHMD")
shell.run("cd VHMD")
shell.run("mkdir modules")
shell.run("wget https://raw.githubusercontent.com/Starlight-CC/VHMD/refs/heads/main/VHMD/init.lua")
shell.run("wget https://raw.githubusercontent.com/Starlight-CC/VHMD/refs/heads/main/VHMD/installModule.lua")
shell.run("wget https://raw.githubusercontent.com/Starlight-CC/VHMD/refs/heads/main/VHMD/update.lua")
shell.run("cd /")
shell.run("VHMD/init.lua")
